services:
  db:
    image: mysql:8.0
    container_name: orellie_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: orellie_wp
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      # Map the theme folder we just built directly into WordPress!
      - ../orellie-theme:/var/www/html/wp-content/themes/orellie-theme
      # Make sure we persist other WP files locally
      - wp_data:/var/www/html
      - ../../resources:/var/www/html/resources

volumes:
  db_data:
  wp_data:
